SELECT M.MAJOR_NAME, TRUNC(AVG(S.SCORE),2) FROM STUDENT S,MAJOR M 
WHERE S.MAJOR_NO = M.MAJOR_NO(+) GROUP BY M.MAJOR_NAME;

SELECT S.SNO, S.SNAME, M.MAJOR_NAME, SS.MONEY 
FROM STUDENT S, MAJOR M, STUDENT_SCHOLARSHIP SS 
WHERE S.MAJOR_NO = M.MAJOR_NO(+) AND S.SNO = SS.STUDENT_NO;